# Thanks to https://oncletom.io/2016/travis-ssh-deploy/ for the tut on travisci ssh deploys

sudo: required

services:
  - docker

addons:
  ssh_known_hosts: 128.199.99.10

script:
  - mvn clean install -Ptest && mvn clean package -DskipTests

before_deploy:
  - openssl aes-256-cbc -K $encrypted_9a783048ece8_key -iv $encrypted_9a783048ece8_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

after_success:
  - docker build -t subjecthub/backend . docker;
    login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag subject/backend yaseenk/subjecthub:latest;
    docker push yaseenk/subjecthub:latest;

deploy:
  provider: script
  skip_cleanup: true
  script: ssh spring@128.199.99.10 'bash /data/run-new-version.sh'
  on:
    branch: master
